// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAocdx9bdgsz_BymhTOnVp-r-LzyP82KoM',
    appId: '1:916603891762:web:619a3f31de7b5a5a3acc2b',
    messagingSenderId: '916603891762',
    projectId: 'brumbella',
    authDomain: 'brumbella.firebaseapp.com',
    storageBucket: 'brumbella.firebasestorage.app',
    measurementId: 'G-T5EF6G5T0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQWFzEert_Hq5VDx7Me7rOaUZpYau9K7w',
    appId: '1:916603891762:android:a04b18b538f3ab4b3acc2b',
    messagingSenderId: '916603891762',
    projectId: 'brumbella',
    storageBucket: 'brumbella.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPWo_1OOAYyeV0UjyV30vdULg2ROVxgDE',
    appId: '1:916603891762:ios:e95bfbdae18ed99e3acc2b',
    messagingSenderId: '916603891762',
    projectId: 'brumbella',
    storageBucket: 'brumbella.firebasestorage.app',
    iosBundleId: 'com.example.brumbella',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPWo_1OOAYyeV0UjyV30vdULg2ROVxgDE',
    appId: '1:916603891762:ios:e95bfbdae18ed99e3acc2b',
    messagingSenderId: '916603891762',
    projectId: 'brumbella',
    storageBucket: 'brumbella.firebasestorage.app',
    iosBundleId: 'com.example.brumbella',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAocdx9bdgsz_BymhTOnVp-r-LzyP82KoM',
    appId: '1:916603891762:web:1b41971feaba00743acc2b',
    messagingSenderId: '916603891762',
    projectId: 'brumbella',
    authDomain: 'brumbella.firebaseapp.com',
    storageBucket: 'brumbella.firebasestorage.app',
    measurementId: 'G-TMR3FNZR74',
  );
}
